### ISSUE TITLE
some bugs in simplecontact plugin

### ISSUE THREAD

**Issue by holosphere** [nunopress/grav-plugin-simple_contact#3]
UPDATE: I just discovered you have to rename the plugin folder to simplecontact (from simple_contact, also when you install it via bin/gpm) and also specify simplecontact: true in the header of your page (rather than simple_contact: true) to make it work.

Also, you need to fix a 'private' declaration in simplecontact.php:162 that was supposed to be 'protected'. [ see:  protected function mergeConfig( Page $page ) ]

Finding this out took me several hours of my working day. 

Please fix the documentation of your plugin and the declaration of mergeConfig. Thanks.
----- old message follows

Hello,
Thanks for making a simple contact plugin. I've installed it, but nothing shows up in my browser when I activate simple_contact:true. I followed your instructions on github to the letter. Tried automatic install and manual install. All to no avail.

Hope you can give me some pointers because I would rather use your simple contact form than the simpleform one.

Yours,

Amadeus de Koning - holosphere r&d

**Comment by namaless** [comment]
If you have a mergeConfig problem i think you not have updated version 1.0.4 into your site, because this is already fixed.

For the other case i have already fixed the "simple_contact: true" for enabled into the page and use configuration instead of page header, but i do not understand where your problem, so please explain me more.

Thanks.

**Comment by holosphere** [comment]
Hi,

Thanks a lot for your reply. I guess "bin/gpm install simple_contact"
pulls in an earlier version. Maybe I did not update it properly, but I
also downloaded the plugin from the grav download page to install
manually, and this did not fix the problem either.

So maybe the package on the grav download page is outdated too?

On 'https://github.com/nunopress/grav-plugin-simple_contact' I read:

----8<----
Also you can override the default options per-page:

---
title: 'My "Page"'

simple_contact:    <=== HERE!
---->8----

But it should be 'simplecontact:', right?

Or perhaps this mixup is all because of my outdated plugin version?

In that case, sorry to have bothered you. My bad.

Yours,

Amadeus de Koning

**Comment by namaless** [comment]
I write to devs for update the site repo but i think not updated because in the site i see the old version 1.0.2 and not 1.0.4 you can see here. With this version (1.0.4) the problem is fixed, what error or problem you have with 1.0.4?

**Comment by erfanimani** [comment]
@holosphere @namaless I think the issue is that bin/gmp pulls in 1.0.2 and not 1.0.4 right?

**Comment by holosphere** [comment]
That's correct.

Thanks for your followup.
